name: Post Release PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - release/next

jobs:
  release_merge:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event }}"
