name: Post Release PR Merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  release_merge:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.review }}"