name: Post Release PR Merge

on: 
  workflow_dispatch:
  pull_request:
    # Patterns matched against refs/heads
    branches:
      - 'release/**'
    types: [ closed ]

jobs:
  release_merge:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RAN"
